### PR TITLE
update recipe and object creation

### PR DESCRIPTION
**Pull request by mtmorgan**
I updated the recipe and metadata to store the original and 'rectangular' h5 files in ExperimentHub; the rowData and colData are meant to be serialized to the package inst/extdata directory

```
TENxBrainData master$ tree
.
├── DESCRIPTION
├── inst
│   ├── extdata
│   │   ├── 1M_neurons_filtered_gene_bc_matrices_h5_colData.rds
│   │   ├── 1M_neurons_filtered_gene_bc_matrices_h5_rowData.rds
│   │   └── metadata.csv
│   └── scripts
│       ├── make-data.R
│       └── make-metadata.R
├── man
│   └── TENxBrainData.Rd
├── NAMESPACE
└── R
    └── TENxBrainData.R

5 directories, 9 files
```
but for some reason I didn't commit them.

One needs to use R-devel, BiocInstaller@3.7.beta (from github.com/Bioconductor), AnnotationHub >= 2.9.22 (via git clone https://git.bioconductor.org/packages/AnnotationHub) (i.e., anticipating the release next week). One gets

```
> TENxBrainData()        ## first time, expensive
snapshotDate(): 2017-10-26
see ?TENxBrainData and browseVignettes('TENxBrainData') for documentation
downloading from ‘https://experimenthub.bioconductor.org/fetch/1040’
retrieving 1 resource
  |======================================================================| 100%

class: SingleCellExperiment 
dim: 27998 1306127 
metadata(0):
assays(1): counts
rownames: NULL
rowData names(2): Ensembl Symbol
colnames(1306127): AAACCTGAGATAGGAG-1 AAACCTGAGCGGCTTC-1 ...
  TTTGTCAGTTAAAGTG-133 TTTGTCATCTGAAAGA-133
colData names(4): Barcode Sequence Library Mouse
reducedDimNames(0):
spikeNames(0):
> sce = TENxBrainData()        ## fast
snapshotDate(): 2017-10-26
see ?TENxBrainData and browseVignettes('TENxBrainData') for documentation
loading from cache ‘/home/mtmorgan//.ExperimentHub/1040’
>

### CODE REVIEW

**Comment by LTLA** [comment]
Thanks Martin. On line 20 of `TENxBrainData.R` it seems that `hfile` gets redefined to a file path in a subdirectory `~/a/`. Is this intended? It seems like an odd place to put a file.

**Comment by mtmorgan** [comment]
Yep, that line https://github.com/LTLA/TENxBrainData/blob/master/R/TENxBrainData.R#L20 shouldn't be there.

**Comment by LTLA** [comment]
Okay, got most of this working. Would you like to commit the various `*.rds` files? I also changed the chunk dimensions to use proportional rectangles, which should allow more efficient access.

**Comment by mtmorgan** [comment]
I think on reflection that I'll arrange for the rds files to be put into ExperimentHub, but yes, I'll update the resources and provide a second pull request when ready.

**Pull request merged**
