### PR TITLE
store row and column data in ExperimentHub

### PR DESCRIPTION
**Pull request by mtmorgan**
- store as data.frame() to avoid risk of S4 class changes
- maybe should be stored in the h5 file directly?

### CODE REVIEW

**Comment by LTLA** [comment]
Thanks Martin. Storage in the HDF5 file would be convenient, but if we're going to do that, it might be better to jump onto some of the other HDF5-based formats which do similar things (e.g., `*.loom`).

**Comment by mtmorgan** [comment]
I pushed an [initial loom parser][1] to SummarizedExperiment. The transpose is expensive in the long run but just a delayed operation in the short term.

[1]: https://github.com/Bioconductor/SummarizedExperiment/commit/732851a87fe0248b2a9b61c90e8605ac51731569

**Comment by LTLA** [comment]
Do we want the parser to live in _SummarizedExperiment_? At this point, it seems like a fairly niche thing that most other SE applications probably won't care about. Maybe there should there be a dedicated _loomR_ package, especially if we want to support more stuff like writing to a `*.loom` file in the future?

**Comment by mtmorgan** [comment]
yes, there's scope for a full package, but I'd rather have a parser now than a package eventually. The parser can move when the package materializes.

**Pull request merged**
